//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocPhi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocSinh()
        {
            this.NopHocPhis = new HashSet<NopHocPhi>();
        }
    
        public int id { get; set; }
        public string TenHocSinh { get; set; }
        public Nullable<int> Lop { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public Nullable<float> TongNo { get; set; }
        public Nullable<int> MaNienKhoa { get; set; }
    
        public virtual Lop Lop1 { get; set; }
        public virtual NienKhoa NienKhoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NopHocPhi> NopHocPhis { get; set; }
    }
}
