//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocPhi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NopHocPhi
    {
        public int id { get; set; }
        public Nullable<int> NguoiNhan { get; set; }
        public Nullable<int> MaHocKy { get; set; }
        public Nullable<int> MaHocSinh { get; set; }
        public System.DateTime ThoiGianNop { get; set; }
        public string NoiDung { get; set; }
        public string GhiChu { get; set; }
        public float SoTien { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual HocSinh HocSinh { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
