//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocPhi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TuitionManagementSoftwareEntities : DbContext
    {
        public TuitionManagementSoftwareEntities()
            : base("name=TuitionManagementSoftwareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HocKy> HocKies { get; set; }
        public virtual DbSet<HocSinh> HocSinhs { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<NienKhoa> NienKhoas { get; set; }
        public virtual DbSet<NopHocPhi> NopHocPhis { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    
        public virtual int sp_AddHocKy(string tenHocKy, Nullable<int> maNienKhoa, Nullable<float> soTien)
        {
            var tenHocKyParameter = tenHocKy != null ?
                new ObjectParameter("tenHocKy", tenHocKy) :
                new ObjectParameter("tenHocKy", typeof(string));
    
            var maNienKhoaParameter = maNienKhoa.HasValue ?
                new ObjectParameter("MaNienKhoa", maNienKhoa) :
                new ObjectParameter("MaNienKhoa", typeof(int));
    
            var soTienParameter = soTien.HasValue ?
                new ObjectParameter("SoTien", soTien) :
                new ObjectParameter("SoTien", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddHocKy", tenHocKyParameter, maNienKhoaParameter, soTienParameter);
        }
    
        public virtual int sp_AddHocSinh(string tenHocSinh, Nullable<int> lop, Nullable<System.DateTime> ngaySinh, string diaChi, Nullable<int> maNienKhoa)
        {
            var tenHocSinhParameter = tenHocSinh != null ?
                new ObjectParameter("tenHocSinh", tenHocSinh) :
                new ObjectParameter("tenHocSinh", typeof(string));
    
            var lopParameter = lop.HasValue ?
                new ObjectParameter("Lop", lop) :
                new ObjectParameter("Lop", typeof(int));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("ngaySinh", ngaySinh) :
                new ObjectParameter("ngaySinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var maNienKhoaParameter = maNienKhoa.HasValue ?
                new ObjectParameter("MaNienKhoa", maNienKhoa) :
                new ObjectParameter("MaNienKhoa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddHocSinh", tenHocSinhParameter, lopParameter, ngaySinhParameter, diaChiParameter, maNienKhoaParameter);
        }
    
        public virtual int sp_AddLop(string tenLop)
        {
            var tenLopParameter = tenLop != null ?
                new ObjectParameter("tenLop", tenLop) :
                new ObjectParameter("tenLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddLop", tenLopParameter);
        }
    
        public virtual int sp_AddNienKhoa(string tenNienKhoa)
        {
            var tenNienKhoaParameter = tenNienKhoa != null ?
                new ObjectParameter("tenNienKhoa", tenNienKhoa) :
                new ObjectParameter("tenNienKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddNienKhoa", tenNienKhoaParameter);
        }
    
        public virtual int sp_AddNopHocPhi(Nullable<int> nguoiNhanTien, Nullable<int> maHocKy, Nullable<int> maHocSinh, Nullable<System.DateTime> thoiGian, string noiDung, string ghiChu, Nullable<float> soTien)
        {
            var nguoiNhanTienParameter = nguoiNhanTien.HasValue ?
                new ObjectParameter("nguoiNhanTien", nguoiNhanTien) :
                new ObjectParameter("nguoiNhanTien", typeof(int));
    
            var maHocKyParameter = maHocKy.HasValue ?
                new ObjectParameter("MaHocKy", maHocKy) :
                new ObjectParameter("MaHocKy", typeof(int));
    
            var maHocSinhParameter = maHocSinh.HasValue ?
                new ObjectParameter("MaHocSinh", maHocSinh) :
                new ObjectParameter("MaHocSinh", typeof(int));
    
            var thoiGianParameter = thoiGian.HasValue ?
                new ObjectParameter("ThoiGian", thoiGian) :
                new ObjectParameter("ThoiGian", typeof(System.DateTime));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var soTienParameter = soTien.HasValue ?
                new ObjectParameter("SoTien", soTien) :
                new ObjectParameter("SoTien", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AddNopHocPhi", nguoiNhanTienParameter, maHocKyParameter, maHocSinhParameter, thoiGianParameter, noiDungParameter, ghiChuParameter, soTienParameter);
        }
    
        public virtual int sp_DeleteHocKy(Nullable<int> maHocKy)
        {
            var maHocKyParameter = maHocKy.HasValue ?
                new ObjectParameter("maHocKy", maHocKy) :
                new ObjectParameter("maHocKy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteHocKy", maHocKyParameter);
        }
    
        public virtual int sp_DeleteHocSinh(Nullable<int> maHocSinh)
        {
            var maHocSinhParameter = maHocSinh.HasValue ?
                new ObjectParameter("maHocSinh", maHocSinh) :
                new ObjectParameter("maHocSinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteHocSinh", maHocSinhParameter);
        }
    
        public virtual int sp_DeleteLop(Nullable<int> malop)
        {
            var malopParameter = malop.HasValue ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteLop", malopParameter);
        }
    
        public virtual int sp_DeleteNienKhoa(Nullable<int> maNienKhoa)
        {
            var maNienKhoaParameter = maNienKhoa.HasValue ?
                new ObjectParameter("maNienKhoa", maNienKhoa) :
                new ObjectParameter("maNienKhoa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteNienKhoa", maNienKhoaParameter);
        }
    
        public virtual int sp_DeleteNopHocPhi(Nullable<int> maNopHoc)
        {
            var maNopHocParameter = maNopHoc.HasValue ?
                new ObjectParameter("MaNopHoc", maNopHoc) :
                new ObjectParameter("MaNopHoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteNopHocPhi", maNopHocParameter);
        }
    
        public virtual int sp_EditHocKy(string tenHocKy, Nullable<int> maNienKhoa, Nullable<float> soTien, Nullable<int> maHocKy)
        {
            var tenHocKyParameter = tenHocKy != null ?
                new ObjectParameter("tenHocKy", tenHocKy) :
                new ObjectParameter("tenHocKy", typeof(string));
    
            var maNienKhoaParameter = maNienKhoa.HasValue ?
                new ObjectParameter("MaNienKhoa", maNienKhoa) :
                new ObjectParameter("MaNienKhoa", typeof(int));
    
            var soTienParameter = soTien.HasValue ?
                new ObjectParameter("SoTien", soTien) :
                new ObjectParameter("SoTien", typeof(float));
    
            var maHocKyParameter = maHocKy.HasValue ?
                new ObjectParameter("maHocKy", maHocKy) :
                new ObjectParameter("maHocKy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditHocKy", tenHocKyParameter, maNienKhoaParameter, soTienParameter, maHocKyParameter);
        }
    
        public virtual int sp_EditHocSinh(string tenHocSinh, Nullable<int> lop, Nullable<System.DateTime> ngaySinh, string diaChi, Nullable<int> maNienKhoa, Nullable<int> maHocSinh)
        {
            var tenHocSinhParameter = tenHocSinh != null ?
                new ObjectParameter("tenHocSinh", tenHocSinh) :
                new ObjectParameter("tenHocSinh", typeof(string));
    
            var lopParameter = lop.HasValue ?
                new ObjectParameter("Lop", lop) :
                new ObjectParameter("Lop", typeof(int));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("ngaySinh", ngaySinh) :
                new ObjectParameter("ngaySinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var maNienKhoaParameter = maNienKhoa.HasValue ?
                new ObjectParameter("MaNienKhoa", maNienKhoa) :
                new ObjectParameter("MaNienKhoa", typeof(int));
    
            var maHocSinhParameter = maHocSinh.HasValue ?
                new ObjectParameter("maHocSinh", maHocSinh) :
                new ObjectParameter("maHocSinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditHocSinh", tenHocSinhParameter, lopParameter, ngaySinhParameter, diaChiParameter, maNienKhoaParameter, maHocSinhParameter);
        }
    
        public virtual int sp_EditLop(Nullable<int> malop, string tenLop)
        {
            var malopParameter = malop.HasValue ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(int));
    
            var tenLopParameter = tenLop != null ?
                new ObjectParameter("tenLop", tenLop) :
                new ObjectParameter("tenLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditLop", malopParameter, tenLopParameter);
        }
    
        public virtual int sp_EditNienKhoa(Nullable<int> maNienKhoa, string tenNienKhoa)
        {
            var maNienKhoaParameter = maNienKhoa.HasValue ?
                new ObjectParameter("maNienKhoa", maNienKhoa) :
                new ObjectParameter("maNienKhoa", typeof(int));
    
            var tenNienKhoaParameter = tenNienKhoa != null ?
                new ObjectParameter("tenNienKhoa", tenNienKhoa) :
                new ObjectParameter("tenNienKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditNienKhoa", maNienKhoaParameter, tenNienKhoaParameter);
        }
    
        public virtual int sp_EditNopHocPhi(Nullable<int> nguoiNhanTien, Nullable<int> maHocKy, Nullable<int> maHocSinh, Nullable<System.DateTime> thoiGian, string noiDung, string ghiChu, Nullable<float> soTien, Nullable<int> maNopHoc)
        {
            var nguoiNhanTienParameter = nguoiNhanTien.HasValue ?
                new ObjectParameter("nguoiNhanTien", nguoiNhanTien) :
                new ObjectParameter("nguoiNhanTien", typeof(int));
    
            var maHocKyParameter = maHocKy.HasValue ?
                new ObjectParameter("MaHocKy", maHocKy) :
                new ObjectParameter("MaHocKy", typeof(int));
    
            var maHocSinhParameter = maHocSinh.HasValue ?
                new ObjectParameter("MaHocSinh", maHocSinh) :
                new ObjectParameter("MaHocSinh", typeof(int));
    
            var thoiGianParameter = thoiGian.HasValue ?
                new ObjectParameter("ThoiGian", thoiGian) :
                new ObjectParameter("ThoiGian", typeof(System.DateTime));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var soTienParameter = soTien.HasValue ?
                new ObjectParameter("SoTien", soTien) :
                new ObjectParameter("SoTien", typeof(float));
    
            var maNopHocParameter = maNopHoc.HasValue ?
                new ObjectParameter("MaNopHoc", maNopHoc) :
                new ObjectParameter("MaNopHoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditNopHocPhi", nguoiNhanTienParameter, maHocKyParameter, maHocSinhParameter, thoiGianParameter, noiDungParameter, ghiChuParameter, soTienParameter, maNopHocParameter);
        }
    }
}
